export const ADD_TO_CART = "ADD TO CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FILTER_BY_RATING="FILTER_BY_RATING"

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const SORT_BY_PRICE = "SORT_BY_PRICE";

